sudo: required
dist: xenial
language: rust

cache: cargo

# build on master or on pull request from different branch, preventing cargo generate error
stages:
  - name: build
    if: branch = master OR type IN (pull_request)

jobs:
  include:
    # Builds with wasm-pack.
    - stage: build
      rust: beta
      env: RUST_BACKTRACE=1
      addons:
        firefox: latest
        chrome: stable
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.5" cargo-generate)
        - cargo install-update -a
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
        - curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
        - sudo apt-get install -y nodejs
        - node -v
        - sudo apt-get install gcc g++ make
      script:
        - cargo generate --git . --name testing
        # Having a broken Cargo.toml (in that it has curlies in fields) anywhere
        # in any of our parent dirs is problematic.
        - mv Cargo.toml Cargo.toml.tmpl
        - cd testing
        - wasm-pack build
        - wasm-pack test --chrome --firefox --headless
        # Since we need to persist the artifacts generated by wasm-pack, do the
        # rest of the build in this stage
        - cd www
        - npm install
        - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: testing/www/dist
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
